### PR TITLE
Fix issue on Bitcoin ListAddressGroupings method

### PR DESCRIPTION
**Pull request by 5he11**
Fix issue on Bitcoin ListAddressGroupings method where balance is not parsed from the response.

### CODE REVIEW

**Comment by 5he11** [comment]
Time to make a NuGet release with recent updates?

**Comment by moodmosaic** [comment]
Very good point. I plan to make a release soon, during the next few days.

**Comment by moodmosaic** [comment]
BitcoinLib 1.7 is now live on NuGet Gallery: https://www.nuget.org/packages/BitcoinLib/ 🚀

**Comment by 5he11** [comment]
It’s awesome to see this new release! Thank you.

________________________________

**Pull request merged**
