### PR TITLE
transaction response add fee field

### PR DESCRIPTION
**Pull request by weitaolee**

### CODE REVIEW

**Comment by GeorgeKimionis** [comment]
Thanks for the PR. I think `Vout` must also be added to `GetTransactionResponseDetails` to complete the signature.

**Comment by GeorgeKimionis** [comment]
`Vout` should be an `Int32` according to this:

    gettransaction "txid" ( includeWatchonly )
    
    Get detailed information about in-wallet transaction <txid>
    
    Arguments:
    1. "txid"    (string, required) The transaction id
    2. "includeWatchonly"    (bool, optional, default=false) Whether to include watchonly addresses in balance calculation and details[]

    Result:
    {
      "amount" : x.xxx,        (numeric) The transaction amount in btc
      "confirmations" : n,     (numeric) The number of confirmations
      "blockhash" : "hash",  (string) The block hash
      "blockindex" : xx,       (numeric) The block index
      "blocktime" : ttt,       (numeric) The time in seconds since epoch (1 Jan 1970 GMT)
      "txid" : "transactionid",   (string) The transaction id.
      "time" : ttt,            (numeric) The transaction time in seconds since epoch (1 Jan 1970 GMT)
      "timereceived" : ttt,    (numeric) The time received in seconds since epoch (1 Jan 1970 GMT)
      "details" : [
        {
          "account" : "accountname",  (string) The account name involved in the transaction, can be "" for the     default account.
          "address" : "bitcoinaddress",   (string) The bitcoin address involved in the transaction
          "category" : "send|receive",    (string) The category, either 'send' or 'receive'
          "amount" : x.xxx                  (numeric) The amount in btc
          "vout" : n,                       (numeric) the vout value
        }
        ,...
      ],
      "hex" : "data"         (string) Raw data for transaction
    }

**Comment by GeorgeKimionis** [comment]
Welcome aboard :)

**Comment by weitaolee** [comment]
tks, @GeorgeKimionis

**Pull request merged**
