### PR TITLE
Dallar integration + Fix for "Move" transactions

### PR DESCRIPTION
**Pull request by Allar**
Added support for the Dallar (http://dallar.org) cryptocurrency.
Fixed "move" transactions crashing the demo app, as they are missing info that is assumed valid in the demo.

### CODE REVIEW

**Comment by Allar** [comment]
I screwed up submitting PRs. Ignore this.

**Comment by Allar** [comment]
The other PR accidentally had this, the move fix, and some readme changes that aren't relevant to your project. My bad, I'm kind of terrible at fork and multi-pr situations.

Due to the way I branched and worked on my fork, I'm not sure I can submit a good PR that isolates these changes?

This PR only contains a Dallar integration as well as the "move" transaction fix. If you do not want to pull in the Dallar integration, simply close this PR and manually pull in the `Program.cs` changes. I don't care about GitHub not tracking that commit as a contribution by me or anything.

**Comment by moodmosaic** [comment]
Don’t worry. Just put the stuff you want in a PR and I’ll sort it out — as long as the PR doesn’t contain massive changes. Those two PRs (or one PR for both) looks OK 👍

**Comment by Allar** [comment]
This PR should now be sorted and good for merging then. Thanks!

**Comment by moodmosaic** [comment]
Thank you, @Allar 💯 This should up on the next NuGet release too, later on this week.

**Comment by moodmosaic** [comment]
This just went live as [BitcoinLib 1.8.0](https://www.nuget.org/packages/BitcoinLib/1.8.0) 🚀

**Pull request merged**
