### PR TITLE
Adding Dogecoin

### PR DESCRIPTION
**Pull request by LeCoffee**
Yay! I did it! It wasn't as hard as I thought if I'm honest. (Sorry if some of the indenting is out it looks fine in my IDE so I know below it looks a little weird but w.e)

### CODE REVIEW

**Comment by GeorgeKimionis** [comment]
Let's sync your code and merge this pull request to the master branch?

**Comment by LeCoffee** [comment]
Is the code still compatible? I've not looked at this in so long, I've recently been using a lot of NodeJS for my cryptocoin apps. I'm just about to goto sleep now but tomorrow I'll take a look and sync up my fork, if all goes well and you approve then sure why not merge it.

**Comment by GeorgeKimionis** [comment]
Sure it is. Let's do this.

Just follow the slightly altered structure in `CoinParameters.cs` and:

- Exclude files: `BitcoinLib.userprefs` and `ConsoleClient.csproj`
- Dismiss `<ProductVersion>`, `<SchemaVersion>` and `<Package>` nodes from `CoinWrapper.csproj` as well as changes in `Program.cs` (only bitcoin is left for demo purposes).

**Comment by GeorgeKimionis** [comment]
This will no longer be necessary. Your code has been [merged](https://github.com/GeorgeKimionis/BitcoinLib/commit/42159427adac7f39e09180b3a2d525a2c033c00b) and [props](https://github.com/GeorgeKimionis/BitcoinLib#credits) have been given. Thank you for your contribution.

**Pull request closed without merging**
