### PR TITLE
Smartcash cryptocurrency support

### PR DESCRIPTION
**Pull request by rc125**
Extendend BitcoinLib with Smartcash support

### CODE REVIEW

**Comment by moodmosaic** [comment]
This looks good and will me merged into `master` over the next couple of days. Thank you! 👍 🚀 🥇

**Comment by moodmosaic** [comment]
Can you please take off a691c2f, 55aafbe, and  0801f69? These commits are basically modifying the README part, in a way that it looks like BitcoinLib is no longer ...BitcoinLib :confused:

**Comment by moodmosaic** [comment]
I guess [`git reset --hard`](https://stackoverflow.com/a/1338744/467754) could work better, instead of closing the pull request.

**Comment by rc125** [comment]
ok @moodmosaic, i will do the next time! ;)

**Comment by moodmosaic** [comment]
No worries :+1:

**Pull request closed without merging**
