### PR TITLE
.NET Core 2.0 Compatibility

### PR DESCRIPTION
**Pull request by nixxholas**

### CODE REVIEW

**Comment by moodmosaic** [comment]
@nixxholas, did you try the `netstandard20` branch? What's in this PR that's not already on that branch? 😕  (Yes, the NuGet Package isn't there; it's going to be done separately.)

**Comment by nixxholas** [comment]
Although not a common practice, this allows users to use the git submodule functionality to add packages into their projects. Hope you consider this option as some institutions mght make changes for custom API modifications.

**Comment by moodmosaic** [comment]
>Although not a common practice, this allows users to use the git submodule functionality

Hmm... This looks interesting 👍 Where is this happening exactly? 😕

**Comment by moodmosaic** [comment]
Okay, I understand this 👍 💯 But your PR contains a whole bunch of other changes(?)

**Comment by nixxholas** [comment]
> Okay, I understand this 👍 💯 But your PR contains a whole bunch of other changes(?)

Will work on refactoring the redundant ones as soon as possible, once im set on my desk!

**Comment by moodmosaic** [comment]
Yeah, that'd be awesome. Actually, for the git submodules thing, I would expect just 1 file change or 2 max.

**Comment by nixxholas** [comment]
> Yeah, that'd be awesome. Actually, for the git submodules thing, I would expect just 1 file change or 2 max.

Infact, its just one file. .csproj, the imported packages has got to be there and that's it, json and sysconfig

**Comment by moodmosaic** [comment]
>Infact, its just one file. .csproj, the imported packages has got to be there and that's it, json and sysconfig

Would you mind opening a PR from your branch to `netstandard20` branch? This way we can easily look at the diff-output and see exactly what those changes are.

**Comment by nixxholas** [comment]
> Would you mind opening a PR from your branch to netstandard20 branch? This way we can easily look at the diff-output and see exactly what those changes are.

Apologies, have OCD here. Prefer to clean up and send a new PR instead, will do so once I clear up some things at hand! =)

**Comment by moodmosaic** [comment]
>Apologies, have OCD here

Exactly—Because I'm *all* into OCD, it's the reason I'm thinking that the best way to tackle this is with a PR from _your_ branch into `netstandard2.0` branch. 👔 

Once we're done with the .NET Standard stuff, we can merge it into `master` branch, but YMMV 😅 😜

**Pull request closed without merging**
