### PR TITLE
GetRawTransactionResponse version

### PR DESCRIPTION
**Pull request by Chaz27**
Fixes transaction
c659729a7fea5071361c2c1a68551ca2bf77679b27086cc415adeeb03852e369 on
Mainnet.  Version is "-1703168784".  Made string to match
DecodeRawTransactionResponse.

### CODE REVIEW

**Comment by GeorgeKimionis** [comment]
Thanks for the PR and for reporting this issue. And you are correct, a signed numerical representation of `version` doesn't really work here. But since `version` will always be numerical and it also reaches towards the `Int32` max value (`2,147,483,647`) I would suggest we turn this into an signed `Int64`. What do you think?

**Comment by Chaz27** [comment]
Yep that makes sense :)

**Comment by GeorgeKimionis** [comment]
Cool. Please update your code accordingly, then we can merge your PR.

**Comment by GeorgeKimionis** [comment]
Thanks for your contribution!

**Pull request merged**
